mongodb:
  image: mongo:latest
  environment:
    - OPLOG_SIZE=1
  ports:
    - "27018:27017"
    - "28018:28017"
registry:
  build: .
  links:
    - mongodb
  ports:
    - "80:80"
  volumes:
    - .:./app
  environment:
    - GITHUB_CLIENT_ID="**changeme**"
    - GITHUB_CLIENT_SECRET="**changeme**"
    - NODE_ENV=production
